import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#b6ebfe",
        secondary: "#006c49",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#2a1700",
        primary: "#003441",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#c0c8cb",
        "on-background": "#0b1c30",
        "on-tertiary-container": "#f8a110",
        surface: "#f8f9ff",
        "on-primary-fixed-variant": "#114d5d",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-container": "#e5eeff",
        "inverse-primary": "#9acee1",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-high": "#dce9ff",
        outline: "#70787c",
        "on-secondary-container": "#00714d",
        "on-tertiary-fixed-variant": "#653e00",
        "error-container": "#ffdad6",
        tertiary: "#452900",
        "tertiary-container": "#643d00",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffddb8",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#002113",
        "inverse-surface": "#213145",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-primary-fixed": "#001f28",
        "surface-tint": "#306576",
        "on-surface": "#0b1c30",
        background: "#f8f9ff",
        "primary-container": "#0f4c5c",
        "inverse-on-surface": "#eaf1ff",
        error: "#ba1a1a",
        "on-primary-container": "#87bbce",
        "primary-fixed-dim": "#9acee1",
        "on-surface-variant": "#40484b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        xs: "4px",
        gutter: "20px",
        base: "8px",
        "container-max": "1120px",
        sm: "12px",
        lg: "40px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "title-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
export default config;
